[package]
name = "deepvol"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
deepbook_predict = { local = "../predict" }
deepbook = { r.mvr = "@deepbook/core", override = true}


[addresses]
deepvol = "0x0"

[environments]
testnet = "4c78adac"
